# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: POK, a real-time kernel for secure embedded systems
email: pok@gunnm.org
description: > # this means to ignore newlines until "baseurl:"
  Website of the POK partitioned operating system
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pok-kernel.github.io" # the base hostname & protocol for your site
github_username:  pok-kernel

# Build settings
markdown: kramdown
